<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);IDE0005</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'HealthTracker.Analyzers'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)src\HealthTracker.Analyzers\HealthTracker.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
